`ifndef ALU_H
`define ALU_H

`define ALU_ADD 5b'00000
`define ALU_UNSIGNED_ADD ALU_ADD
`define ALU_SUB 5b'00001
`define ALU_UNSIGNED_SUB ALU_SUB

`define ALU_AND 5b'10000
`define ALU_BITWISE_AND ALU_AND
`define ALU_OR 5b'10001
`define ALU_BITWISE_OR ALU_OR
`define ALU_NOT 5b'10010
`define ALU_BITWISE_NOT ALU_NOT
`define ALU_XOR 5b'10011
`define ALU_BITWISE_XOR ALU_XOR

`define ALU_LOGICAL_AND 5b'11000
`define ALU_LOGICAL_OR 5b'11001
`define ALU_LOGICAL_NOT 5b'11010

`define ALU_EQUAL 2b'00
`define ALU_EQUAL_TO ALU_EQUAL
`define ALU_LARGER 2b'01
`define ALU_LARGER_THAN ALU_LARGER
`define ALU_SMALLER 2b'10
`define ALU_SMALLER_THAN ALU_SMALLER

`define ALU_OVERFLOW 1'b1
`define ALU_NOT_OVERFLOW 1'b0

`define ALU_INVALID_OP 1'b1
`define ALU_INVALID ALU_INVALID_OP
`define ALU_VALID_OP 1'b0
`define ALU_VALID ALU_VALID_OP

`endif

