`ifndef DM_H
`define DM_H

`define DM_WRITE_ENABLE 1'b1
`define DM_WRITE_ENABLED DM_WRITE_ENABLE
`define DM_WRITE_DISABLE 1'b0
`define DM_WRITE_DISABLED DM_WRITE_DISABLE

`define DM_ADDR_WIDTH 8
`define DM_SIZE 64

`endif

