`ifndef EXT_H
`define EXT_H

`define EXT_MODE_SIGNED 3'b000
`define EXT_SIGNED `EXT_MODE_SIGNED
`define EXT_MODE_UNSIGNED 3'b001
`define EXT_UNSIGNED `EXT_MODE_UNSIGNED
`define EXT_MODE_PAD 3'b010
`define EXT_PAD `EXT_MODE_PAD
`define EXT_MODE_HIGH_BITS `EXT_MODE_PAD
`define EXT_HIGH_BITS `EXT_MODE_PAD
`define EXT_MODE_ONE 3'b011
`define EXT_ONE `EXT_MODE_ONE

`endif

