`ifndef NPC_H
`define NPC_H

`define NPC_JUMP_DISABLE 3'b000
`define NPC_JUMP_DISABLED `NPC_JUMP_DISABLE
`define NPC_JUMP_WHEN_EQUAL 3'b001
`define NPC_JUMP_WHEN_EQUALS_TO `NPC_JUMP_WHEN_EQUAL
`define NPC_JUMP_WHEN_NOT_EQUAL 3'b010
`define NPC_JUMP_WHEN_NOT_EQUALS_TO `NPC_JUMP_WHEN_NOT_EQUAL
`define NPC_JUMP_JNUM 3'b011

`endif

