`ifndef RF_H
`define RF_H

`define RF_ADDR_ZERO 5'b0
`define RF_ZERO 5'b0
`define RF_WRITE_ENABLED 1'b1
`define RF_WRITE_ENABLE RF_WRITE_ENABLED
`define RF_WRITE_DISABLED 1'b0
`define RF_WRITE_DISABLE RF_WRITE_DISABLED

`endif

